name: Alcazar
author: oko
description: Alcazar is a PvP utility plugin, inspired by DevotedPvP.
website: https://oko.moe
version: 0.2.0
main: moe.oko.alcazar.Alcazar
api-version: 1.17
commands:
  inv:
    permission: alcazar.inventory
    description: inv.
    usage: /<command>
    aliases: [ inventory ]
permissions:
  alcazar.admin:
    default: op
  alcazar.inventory:
    default: true